lcmImage: "lcm-server-insight-webapp"
lcmImageTag: "engr-525"

waitHosts: "180"
dbUser: "root"
dbPassword: "password"
dbDriver: "com.mysql.jdbc.Driver"
lcmDocsVersion: "1.0.0.38"
dbMaxActive: "100"
dbMaxIdle: "100"
dbMaxWait: "30000"
dbEvictionInterval: "5000"
dbRemoveAbandoned: "true"

imagePullPolicy: Always

nodeSelector: {}

livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

readinessProbe:
  initialDelaySeconds: 5
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 3

persistence:
  enabled: false
  accessMode: ReadWriteOnce
  size: 8Gi

resources:
  requests:
    memory: 256Mi
    cpu: 100m

service:
  type: ClusterIP
  port: 3306
