apiVersion: v1
kind: ConfigMap
metadata:
  name: '{{ template "lcm.fullname" . }}-config' # Need to revisit this
data:
  WAIT_HOSTS_TIMEOUT: "180"
  WAIT_HOSTS: "lcm-mysql:3306,apacheds:10389,cas:8081"
  DB_MAX_ACTIVE: "100"
  DB_MAX_IDLE: "100"
  DB_MAX_WAIT: "30000"
  DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS: "5000"
  DB_REMOVE_ABANDONED: "true"
  DB_USER: root
  DB_PASSWORD: password
  DB_HOST:
  DATABASE_DUMP:
  DB_DRIVER: "com.mysql.jdbc.Driver"
  DB_URL: jdbc:mysql://lcm-mysql:3306
  CAS_SERVER_LOCATION: https://lcm.k8s.c7ks7s.com/cas
  LCM_SERVER_LOCATION: https://lcm.k8s.c7ks7s.com/lcm
  HELP_SERVER_LOCATION: https://lcm.k8s.c7ks7s.com/lcm/help
  LCM_DOCS_VERSION: "1.0.0.38"
  CAS_EXT_PORT: "443"
  LCM_EXT_PORT: "443"
  LCM_VERSION:
  LCM_TENANT_VERSION:
  TENANTS:
  SIMULATION_ENGINE_HOST:
  DEMANDPRO_PORT:
  SERVER_NAME:
